FROM python:3.6

WORKDIR /workdir

# Copy project files
COPY src src
COPY Pipfile .
COPY Pipfile.lock .

# Install pipenv and dependencies
RUN pip install pipenv
RUN pipenv install

# Copy scripts
COPY scripts/ /usr/local/bin
