version: "3"

services:
  webserver:
    build:
      context: .
      dockerfile: ./docker/webserver/Dockerfile
      args:
        WAIT_FOR_SCRIPT: ./docker/wait-for-it
        STARTUP_SCRIPT: ./docker/webserver/django-migrate-and-runserver
    volumes:
      - .:/workdir
    ports:
      - 8000:8000
    depends_on:
      - database
    command: wait-for-it database:5432 --timeout=0 -- django-migrate-and-runserver secomplican 8000 

  database:
    build:
      context: .
      dockerfile: ./docker/database/Dockerfile
    ports:
      - "5432:5432"
