# Generated by Django 2.0.5 on 2018-05-08 19:30

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConjuntoDeEnunciados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cuatrimestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('numero', models.IntegerField(choices=[(1, 'Primer Cuatrimestre'), (2, 'Segundo Cuatrimestre'), (3, 'Verano')])),
            ],
        ),
        migrations.CreateModel(
            name='Enunciado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1023)),
            ],
        ),
        migrations.CreateModel(
            name='Solucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enunciados.Enunciado')),
            ],
        ),
        migrations.CreateModel(
            name='VersionTextoEnunciado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo', models.DateTimeField(auto_now_add=True)),
                ('texto', models.TextField()),
                ('enunciado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='enunciados.Enunciado')),
            ],
            options={
                'ordering': ['-tiempo'],
                'abstract': False,
            },
            managers=[
                ('versiones', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='VersionTextoSolucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo', models.DateTimeField(auto_now_add=True)),
                ('texto', models.TextField()),
                ('solucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='enunciados.Solucion')),
            ],
            options={
                'ordering': ['-tiempo'],
                'abstract': False,
            },
            managers=[
                ('versiones', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Final',
            fields=[
                ('conjuntodeenunciados_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='enunciados.ConjuntoDeEnunciados')),
                ('fecha', models.DateField()),
            ],
            bases=('enunciados.conjuntodeenunciados',),
        ),
        migrations.CreateModel(
            name='Parcial',
            fields=[
                ('conjuntodeenunciados_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='enunciados.ConjuntoDeEnunciados')),
                ('numero', models.IntegerField()),
                ('fecha', models.DateField(blank=True, null=True)),
                ('recuperatorio', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('enunciados.conjuntodeenunciados',),
        ),
        migrations.CreateModel(
            name='Practica',
            fields=[
                ('conjuntodeenunciados_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='enunciados.ConjuntoDeEnunciados')),
                ('numero', models.IntegerField()),
                ('titulo', models.CharField(default='', max_length=1023)),
            ],
            options={
                'abstract': False,
            },
            bases=('enunciados.conjuntodeenunciados',),
        ),
        migrations.AddField(
            model_name='enunciado',
            name='conjunto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enunciados.ConjuntoDeEnunciados'),
        ),
        migrations.AlterUniqueTogether(
            name='cuatrimestre',
            unique_together={('anio', 'numero')},
        ),
        migrations.AddField(
            model_name='conjuntodeenunciados',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enunciados.Materia'),
        ),
        migrations.AddField(
            model_name='practica',
            name='cuatrimestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enunciados.Cuatrimestre'),
        ),
        migrations.AddField(
            model_name='parcial',
            name='cuatrimestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enunciados.Cuatrimestre'),
        ),
        migrations.AlterUniqueTogether(
            name='enunciado',
            unique_together={('numero', 'conjunto')},
        ),
    ]
