# Generated by Django 2.1 on 2018-08-09 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enunciados', '0002_auto_20180804_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuatrimestre',
            name='numero',
            field=models.IntegerField(choices=[(3, 'Verano'), (1, 'Primer Cuatrimestre'), (2, 'Segundo Cuatrimestre')]),
        ),
    ]
