# Generated by Django 2.1 on 2018-08-18 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enunciados', '0008_auto_20180818_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='optativa',
            field=models.BooleanField(default=False),
        ),
    ]
