# Generated by Django 2.1.1 on 2018-09-14 04:50

from django.db import migrations, models
import django.db.models.deletion

# Generated by Django 2.1.1 on 2018-09-14 04:22

from django.db import migrations, models
import django.db.models.deletion


def crear_uba(apps, schema_editor):
    Universidad = apps.get_model('enunciados', 'Universidad')
    db_alias = schema_editor.connection.alias
    Universidad.objects.using(db_alias).create(
        nombre='Universidad de Buenos Aires (UBA)',
        slug='uba',
    )


def eliminar_uba(apps, schema_editor):
    Universidad = apps.get_model('enunciados', 'Universidad')
    db_alias = schema_editor.connection.alias
    Universidad.objects.using(db_alias).filter(
        nombre='Universidad de Buenos Aires (UBA)',
        slug='uba',
    ).delete()


def crear_computacion(apps, schema_editor):
    Universidad = apps.get_model('enunciados', 'Universidad')
    Carrera = apps.get_model('enunciados', 'Carrera')
    db_alias = schema_editor.connection.alias
    uba = Universidad.objects.using(db_alias).get(slug='uba')
    Carrera.objects.using(db_alias).create(
        universidad=uba,
        nombre='Ciencias de la Computación',
        slug='computacion',
    )


def eliminar_computacion(apps, schema_editor):
    Carrera = apps.get_model('enunciados', 'Carrera')
    db_alias = schema_editor.connection.alias
    Carrera.objects.using(db_alias).filter(
        universidad__nombre='Universidad de Buenos Aires (UBA)',
        universidad__slug='uba',
        nombre='Ciencias de la Computación',
        slug='computacion',
    ).delete()


def materia_a_materiacarrera(apps, schema_editor):
    Universidad = apps.get_model('enunciados', 'Universidad')
    Carrera = apps.get_model('enunciados', 'Carrera')
    Materia = apps.get_model('enunciados', 'Materia')
    MateriaCarrera = apps.get_model('enunciados', 'MateriaCarrera')
    db_alias = schema_editor.connection.alias
    compu = Carrera.objects.using(db_alias).get(slug='computacion')
    materiacarreras = [
        MateriaCarrera(
            carrera=compu,
            materia=materia,
            nombre=materia.nombre,
            slug=materia.slug,
            optativa=materia.optativa,
        ) for materia in Materia.objects.using(db_alias).all()
    ]
    MateriaCarrera.objects.using(db_alias).bulk_create(materiacarreras)


class Migration(migrations.Migration):

    dependencies = [
        ('enunciados', '0011_auto_20180913_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1023)),
                ('slug', models.CharField(max_length=1023)),
            ],
        ),
        migrations.CreateModel(
            name='MateriaCarrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1023)),
                ('slug', models.SlugField(max_length=1023)),
                ('optativa', models.BooleanField(default=False)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enunciados.Carrera')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1023)),
                ('slug', models.SlugField(max_length=1023, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='materiacarrera',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enunciados.Materia'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='materias',
            field=models.ManyToManyField(through='enunciados.MateriaCarrera', to='enunciados.Materia'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='universidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enunciados.Universidad'),
        ),
        migrations.AlterUniqueTogether(
            name='materiacarrera',
            unique_together={('carrera', 'materia'), ('carrera', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='carrera',
            unique_together={('universidad', 'slug')},
        ),

        migrations.RunPython(crear_uba, eliminar_uba),
        migrations.RunPython(crear_computacion, eliminar_computacion),
        migrations.RunPython(materia_a_materiacarrera),

        migrations.AlterModelOptions(
            name='materia',
            options={},
        ),
        migrations.RemoveField(
            model_name='materia',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='optativa',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='slug',
        ),
    ]
