# Generated by Django 2.2.2 on 2019-12-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enunciados', '0013_informacionusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='enunciado',
            name='votos',
            field=models.IntegerField(default=0),
        ),
    ]
