# Generated by Django 2.2.2 on 2019-12-31 00:28

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


def version_texto_solucion_a_version_texto(apps, schema_editor):
    VersionTextoSolucion = apps.get_model('enunciados', 'VersionTextoSolucion')
    VersionTexto = apps.get_model('enunciados', 'VersionTexto')
    for version_texto_solucion in VersionTextoSolucion.versiones.all():
        VersionTexto.versiones.create(
            tiempo=version_texto_solucion.tiempo,
            texto=version_texto_solucion.texto,
            posteo=version_texto_solucion.solucion.posteo)


def version_texto_enunciado_a_version_texto(apps, schema_editor):
    VersionTextoEnunciado = apps.get_model('enunciados', 'VersionTextoEnunciado')
    VersionTexto = apps.get_model('enunciados', 'VersionTexto')
    for version_texto_enunciado in VersionTextoEnunciado.versiones.all():
        VersionTexto.versiones.create(
            tiempo=version_texto_enunciado.tiempo,
            texto=version_texto_enunciado.texto,
            posteo=version_texto_enunciado.enunciado.posteo)


class Migration(migrations.Migration):

    dependencies = [
        ('enunciados', '0016_posteos_ELIMINA_ENUNCIADOS'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionTexto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo', models.DateTimeField(auto_now_add=True)),
                ('texto', models.TextField()),
                ('posteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='enunciados.Posteo')),
            ],
            options={
                'ordering': ['-tiempo'],
            },
            managers=[
                ('versiones', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunPython(version_texto_enunciado_a_version_texto),
        migrations.RunPython(version_texto_solucion_a_version_texto),
        migrations.RemoveField(
            model_name='versiontextosolucion',
            name='solucion',
        ),
        migrations.DeleteModel(
            name='VersionTextoEnunciado',
        ),
        migrations.DeleteModel(
            name='VersionTextoSolucion',
        ),
    ]
