# Generated by Django 2.2.2 on 2020-01-02 04:48

from django.conf import settings
from django.db import migrations, models
import enunciados.models.models


def crear_deleted(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    User.objects.create(username='Eliminado')


def eliminar_deleted(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    User.objects.get(username='Eliminado').delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enunciados', '0020_auto_20200102_0048'),
    ]

    operations = [
        migrations.RunPython(crear_deleted, eliminar_deleted)
    ]
