# Generated by Django 2.2.2 on 2020-01-02 04:54

from django.conf import settings
from django.db import migrations, models
import enunciados.models.models


def setear_todos_en_deleted(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Solucion = apps.get_model('enunciados', 'Solucion')
    eliminado = User.objects.get(username='Eliminado')
    for solucion in Solucion.objects.all():
        solucion.creador = eliminado
        solucion.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enunciados', '0021_usuario_eliminado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solucion',
            name='creador',
            field=models.ForeignKey(null=True, on_delete=models.SET(enunciados.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RunPython(setear_todos_en_deleted, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="solucion",
            name="creador",
            field=models.ForeignKey(
                null=False,
                on_delete=models.SET(enunciados.models.get_sentinel_user),
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
