# Generated by Django 2.2.2 on 2020-01-16 23:36

from django.conf import settings
from django.db import migrations, models
from enunciados.models.models import get_sentinel_user


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enunciados', '0023_auto_20200109_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='versiontexto',
            name='autor',
            field=models.ForeignKey(
                null=True,
                on_delete=models.SET(get_sentinel_user),
                to=settings.AUTH_USER_MODEL),
        ),
    ]
