# Generated by Django 2.2.2 on 2020-01-16 23:44

from django.db import migrations


def set_sentinel_user_en_autor_version_texto(apps, schema_editor):
    VersionTexto = apps.get_model('enunciados', 'VersionTexto')
    User = apps.get_model('auth', 'User')
    sentinel = User.objects.get(username='Eliminado')
    for version in VersionTexto.versiones.all():
        version.autor = sentinel
        version.save()


class Migration(migrations.Migration):

    dependencies = [
        ('enunciados', '0024_versiontexto_autor'),
    ]

    operations = [
        migrations.RunPython(
            set_sentinel_user_en_autor_version_texto, reverse_code=migrations.RunPython.noop),
    ]
