# Generated by Django 3.0.5 on 2020-05-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enunciados', '0031_auto_20200502_1424'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='enunciado',
            constraint=models.CheckConstraint(check=models.Q(numero__gt=0), name='numero_positivo'),
        ),
    ]
