# Generated by Django 2.1 on 2018-05-01 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enunciado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('cuatrimestre', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1023)),
            ],
        ),
        migrations.CreateModel(
            name='Practica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enunciados.Etapa')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enunciados.Materia')),
            ],
        ),
        migrations.CreateModel(
            name='Solucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('enunciado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enunciados.Enunciado')),
            ],
        ),
        migrations.AddField(
            model_name='enunciado',
            name='practica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enunciados.Practica'),
        ),
    ]
