# Generated by Django 2.1 on 2018-05-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enunciados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practica',
            name='numero',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practica',
            name='titulo',
            field=models.CharField(default='', max_length=1023),
        ),
    ]
