# Generated by Django 2.0.7 on 2018-08-04 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enunciados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solucion',
            name='enunciado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soluciones', to='enunciados.Enunciado'),
        ),
    ]
