# Generated by Django 2.0.5 on 2018-05-04 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enunciados', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enunciado',
            options={'ordering': ['numero']},
        ),
    ]
