# Generated by Django 2.1 on 2018-05-02 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enunciados', '0002_auto_20180501_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='enunciado',
            name='numero',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='etapa',
            name='cuatrimestre',
            field=models.IntegerField(choices=[(1, 'Primer Cuatrimestre'), (2, 'Segundo Cuatrimestre'), (3, 'Verano')]),
        ),
    ]
