# Generated by Django 2.0.5 on 2018-05-04 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enunciados', '0002_auto_20180504_0211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuatrimestre',
            old_name='cuatrimestre',
            new_name='numero',
        ),
    ]
