# Generated by Django 2.0.5 on 2018-05-07 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enunciados', '0003_auto_20180504_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionTexto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo', models.DateTimeField(auto_now_add=True)),
                ('texto', models.TextField()),
            ],
            options={
                'ordering': ['-tiempo'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='cuatrimestre',
            unique_together={('anio', 'numero')},
        ),
        migrations.RemoveField(
            model_name='enunciado',
            name='texto',
        ),
        migrations.AlterUniqueTogether(
            name='enunciado',
            unique_together={('numero', 'conjunto')},
        ),
        migrations.AddField(
            model_name='versiontexto',
            name='enunciado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='enunciados.Enunciado'),
        ),
    ]
