# Generated by Django 2.0.5 on 2018-05-03 02:50

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('enunciados', '0003_auto_20180502_0128'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Etapa',
            new_name='Cuatrimestre',
        ),
        migrations.RenameField(
            model_name='practica',
            old_name='etapa',
            new_name='cuatrimestre',
        ),
    ]
