# Generated by Django 2.1 on 2018-08-10 21:41

from django.db import migrations, models


def pasar_anio_y_cuatrimestre_model(apps, schema_editor, nombre_model):
    Model = apps.get_model('enunciados', nombre_model)
    for parcial in Model.objects.all():
        parcial.anio = parcial.cuatrimestre.anio
        parcial.cuatrimestre_nuevo = parcial.cuatrimestre.numero
        parcial.save()


def pasar_anio_y_cuatrimestre(apps, schema_editor):
    pasar_anio_y_cuatrimestre_model(apps, schema_editor, 'Parcial')
    pasar_anio_y_cuatrimestre_model(apps, schema_editor, 'Practica')


class Migration(migrations.Migration):
    dependencies = [
        ('enunciados', '0004_auto_20180810_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcial',
            name='anio',
            field=models.IntegerField(default=2018),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practica',
            name='anio',
            field=models.IntegerField(default=2018),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcial',
            name='cuatrimestre_nuevo',
            field=models.IntegerField(choices=[(3, 'Verano'), (1, 'Primer Cuatrimestre'), (2, 'Segundo Cuatrimestre')],
                                      default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practica',
            name='cuatrimestre_nuevo',
            field=models.IntegerField(choices=[(3, 'Verano'), (1, 'Primer Cuatrimestre'), (2, 'Segundo Cuatrimestre')],
                                      default=1),
            preserve_default=False,
        ),
        migrations.RunPython(pasar_anio_y_cuatrimestre),
        migrations.RemoveField(
            model_name='practica',
            name='cuatrimestre',
        ),
        migrations.RemoveField(
            model_name='parcial',
            name='cuatrimestre',
        ),
        migrations.DeleteModel(
            name='Cuatrimestre',
        ),
        migrations.RenameField(
            model_name='parcial',
            old_name='cuatrimestre_nuevo',
            new_name='cuatrimestre',
        ),
        migrations.RenameField(
            model_name='practica',
            old_name='cuatrimestre_nuevo',
            new_name='cuatrimestre',
        ),
    ]
