# Generated by Django 2.0.5 on 2018-05-07 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enunciados', '0005_auto_20180507_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solucion',
            name='texto',
        ),
    ]
