# Generated by Django 2.0.5 on 2018-05-08 03:18

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('enunciados', '0006_remove_solucion_texto'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='versiontextoenunciado',
            managers=[
                ('versiones', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='versiontextosolucion',
            managers=[
                ('versiones', django.db.models.manager.Manager()),
            ],
        ),
    ]
