# Generated by Django 2.1 on 2018-08-18 03:50

from django.db import migrations
from django.utils.text import slugify


MATERIAS = [
    'Análisis II', 'Álgebra', 'Algoritmos y Estructuras de Datos I',
    'Probabilidad y Estadística', 'Algoritmos y Estructuras de Datos II',
    'Organización del Computador I', 'Métodos Numéricos',
    'Organización del Computador II', 'Algoritmos y Estructuras de Datos III',
    'Sistemas Operativos', 'Lógica y Computabilidad',
    'Teoría de las Comunicaciones (Redes)', 'Ingeniería de Software I',
    'Bases de Datos', 'Teoría de Lenguajes', 'Paradigmas de Programación',
    'Ingeniería de Software II',
]


def agregar_materias(apps, schema_editor):
    """Agrega las materias del tronco común de Cs. de la Computación."""
    Materia = apps.get_model('enunciados', 'Materia')
    for nombre_materia in MATERIAS:
        slug = slugify(nombre_materia)
        Materia(nombre=nombre_materia, slug=slug).save()


def sacar_materias(apps, schema_editor):
    Materia = apps.get_model('enunciados', 'Materia')
    for nombre_materia in MATERIAS:
        Materia.objects.get(nombre=nombre_materia).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('enunciados', '0006_materia_slug'),
    ]

    operations = [
        migrations.RunPython(agregar_materias, sacar_materias)
    ]
