# Generated by Django 2.0.5 on 2018-05-08 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enunciados', '0007_auto_20180508_0318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Final',
            fields=[
                ('conjuntodeenunciados_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='enunciados.ConjuntoDeEnunciados')),
                ('fecha', models.DateField()),
            ],
            bases=('enunciados.conjuntodeenunciados',),
        ),
        migrations.RemoveField(
            model_name='conjuntodeenunciados',
            name='cuatrimestre',
        ),
        migrations.AddField(
            model_name='parcial',
            name='cuatrimestre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='enunciados.Cuatrimestre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practica',
            name='cuatrimestre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='enunciados.Cuatrimestre'),
            preserve_default=False,
        ),
    ]
