# Generated by Django 2.1 on 2018-08-18 04:12

from django.db import migrations
from django.utils.text import slugify


# Materias optativas del 1er cuatri del 2018
MATERIAS = [
    'Arquitectura y Comunicación de Datos', 'Arquitecturas Web',
    'Integración de Bases de Conocimiento', 'Introducción a la Robótica Móvil',
    'Investigación Operativa',
    'Problemas de Grafos y Tratabilidad Computacional',
    'Seminario de Análisis de Programas', 'Procesamiento de Señales',
    'Reconocimiento de Patrones', 'Redes Neuronales',
    'Seguridad de la Información',
    'Seminario Avanzado sobre Modelos y Algoritmos para el Análisis de Sistemas',
    'Seminario de Síntesis de Controladores',
]


def agregar_materias(apps, schema_editor):
    """Agrega las materias optativas a la base de datos."""
    Materia = apps.get_model('enunciados', 'Materia')
    for nombre_materia in MATERIAS:
        slug = slugify(nombre_materia)
        Materia(nombre=nombre_materia, slug=slug, optativa=True).save()


def sacar_materias(apps, schema_editor):
    Materia = apps.get_model('enunciados', 'Materia')
    for nombre_materia in MATERIAS:
        slug = slugify(nombre_materia)
        Materia.objects.get(nombre=nombre_materia, optativa=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('enunciados', '0009_materia_optativa'),
    ]

    operations = [
        migrations.RunPython(agregar_materias, sacar_materias),
    ]
