# Generated by Django 2.1.1 on 2018-09-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enunciados', '0010_materias_optativas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcial',
            name='cuatrimestre',
            field=models.IntegerField(choices=[(0, 'Verano'), (1, 'Primer Cuatrimestre'), (2, 'Segundo Cuatrimestre')]),
        ),
        migrations.AlterField(
            model_name='practica',
            name='cuatrimestre',
            field=models.IntegerField(choices=[(0, 'Verano'), (1, 'Primer Cuatrimestre'), (2, 'Segundo Cuatrimestre')]),
        ),
    ]
