# Generated by Django 2.2.2 on 2019-12-27 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def agregar_informacion(apps, schema_editor):
    """Crea una InformacionUsuario por cada User"""
    User = apps.get_model('auth', 'User')
    InformacionUsuario = apps.get_model('enunciados', 'InformacionUsuario')
    for usuario in User.objects.all():
        InformacionUsuario(usuario=usuario).save()

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enunciados', '0012_auto_20180914_0150'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacionUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.PositiveIntegerField(default=0)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(agregar_informacion),
    ]
