# Generated by Django 2.2.2 on 2019-12-31 00:12

from django.db import migrations, models
import django.db.models.deletion


def eliminar_enunciados_y_soluciones(apps, schema_editor):
    """
    Me aburrí de tratar de hacer que los enunciados se pasen a ser posteos,
    así que limpio todo y fue.
    """
    Enunciado = apps.get_model('enunciados', 'Enunciado')
    Solucion = apps.get_model('enunciados', 'Solucion')
    Enunciado.objects.all().delete()
    Solucion.objects.all().delete()


# def agregar_posteo_default(apps, schema_editor):
#     Posteo = apps.get_model('enunciados', 'Posteo')
#     Posteo.objects.create()


# def eliminar_posteo_default(apps, schema_editor):
#     Posteo = apps.get_model('enunciados', 'Posteo')
#     Posteo.objects.get(id=1).delete()


# def agregar_posteos_a_enunciados(apps, schema_editor):
#     Enunciado = apps.get_model('enunciados', 'Enunciado')
#     Posteo = apps.get_model('enunciados', 'Posteo')
#     for enunciado in Enunciado.objects.all():
#         posteo = Posteo.objects.create(puntos=enunciado.votos)
#         enunciado.delete() # Porque hay una restriccion de numero, conjunto_id
#         enunciado.posteo_ptr = posteo
#         enunciado.save()


# def sacar_posteos_a_enunciados(apps, schema_editor):
#     Enunciado = apps.get_model('enunciados', 'Enunciado')
#     Posteo = apps.get_model('enunciados', 'Posteo')
#     for enunciado in Enunciado.objects.all():
#         posteo = Posteo.objects.filter(enunciado=enunciado)
#         enunciado.votos = posteo.puntos
#         enunciado.save()


# def agregar_posteos_a_soluciones(apps, schema_editor):
#     Solucion = apps.get_model('enunciados', 'Solucion')
#     Posteo = apps.get_model('enunciados', 'Posteo')
#     for solucion in Solucion.objects.all():
#         posteo = Posteo.objects.create()
#         solucion.posteo_ptr = posteo
#         solucion.save()


# def sacar_posteos_a_soluciones(apps, schema_editor):
#     Solucion = apps.get_model('enunciados', 'Solucion')
#     Posteo = apps.get_model('enunciados', 'Posteo')
#     for solucion in Solucion.objects.all():
#         posteo = Posteo.objects.filter(solucion=solucion)
#         solucion.save()


class Migration(migrations.Migration):

    dependencies = [
        ('enunciados', '0015_auto_20191228_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posteo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField(default=0)),
            ],
        ),
        migrations.RunPython(eliminar_enunciados_y_soluciones, migrations.RunPython.noop),
        migrations.RenameField(
            model_name='solucion',
            old_name='enunciado',
            new_name='enunciado_padre',
        ),
        migrations.RemoveField(
            model_name='enunciado',
            name='id',
        ),
        migrations.RemoveField(
            model_name='solucion',
            name='id',
        ),
        migrations.AddField(
            model_name='enunciado',
            name='posteo_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='enunciados.Posteo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solucion',
            name='posteo_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='enunciados.Posteo'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='enunciado',
            name='votos',
        ),
    ]
