# Generated by Django 2.2.2 on 2020-01-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enunciados', '0018_auto_20191230_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posteo',
            name='puntos',
        ),
        migrations.AddField(
            model_name='solucion',
            name='puntos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
