# Generated by Django 2.2.2 on 2020-01-02 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enunciados', '0019_auto_20200102_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voto',
            name='posteo',
        ),
        migrations.AddField(
            model_name='voto',
            name='solucion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='enunciados.Solucion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='informacionusuario',
            name='votos',
            field=models.ManyToManyField(through='enunciados.Voto', to='enunciados.Solucion'),
        ),
    ]
