# Generated by Django 2.2.2 on 2020-01-16 23:50

from django.conf import settings
from django.db import migrations, models
from enunciados.models.models import get_sentinel_user


class Migration(migrations.Migration):

    dependencies = [
        ('enunciados', '0025_usuario_eliminado_en_version_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versiontexto',
            name='autor',
            field=models.ForeignKey(on_delete=models.SET(get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
